# This is the docker compose I used for establishing a connection between the Docker container with the image of Neo4J
# and the localhost of Neo4J Browser
# The URL of the localhost is http://localhost:7001/browser/ and in Neo4j Browser it is possible to connect via
# bolt://localhost:7002 and Authentication type Username / Password and leaving the fields empty.

version: '5.14'

services:
  db:
    image: neo4j:latest
    container_name: knowledge-graph-db
    ports:
      - "7001:7474"
      - "7002:7687"
    volumes:
      - ./volumes/neo4j:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/var/lib/neo4j/import
      - ./volumes/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_apoc_export_file_enabled=true
    networks:
      - feenstaub_network

networks:
  feenstaub_network:
    driver: bridge



